name: Aptabase CI
on: push

permissions:
  id-token: write
  packages: write
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: aptabase:latest
          outputs: type=docker,dest=/tmp/aptabase.tar

      - name: Upload Image
        uses: actions/upload-artifact@v3
        with:
          name: aptabase
          path: /tmp/aptabase.tar

  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Publish
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download Image
        uses: actions/download-artifact@v3
        with:
          name: aptabase
          path: /tmp

      - name: Load Image
        run: docker load --input /tmp/aptabase.tar

      # Push to Public Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        run: |
          docker tag aptabase:latest $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        env:
          REGISTRY: ghcr.io/aptabase
          REPOSITORY: aptabase
          IMAGE_TAG: main
